<main id="edit-user">  
    <h2>Modifier un utilisateur</h2>
    <form action="/ZERODEGRE_/admin/user/edit&id=<?= $_GET['id'] ?>" method="post">
        <p class="form-errors">
            <?php
                if(isset($data['errors']))
                    echo $data["errors"][0];
            ?>
        </p>
        <fieldset>
            <label for="edit-firstName">
                Prénom
            </label>
            <input type="text" name="edit-firstName" id="edit-firstName"/>
        </fieldset>
        <fieldset>
            <label for="edit-lastName">
                Nom
            </label>
            <input type="text" name="edit-lastName" id="edit-lastName"/>
        </fieldset>
        <fieldset>
            <label for="edit-email">
                Email
            </label>
            <input type="email" name="edit-email" id="edit-email"/>
        </fieldset>
        <fieldset>
            <label for="edit-password">
                Mot de passe
            </label>
            <input type="password" name="edit-password" id="edit-password"/>
        </fieldset>
        <fieldset>
            <label for="edit-confirm-password">
                 Confirmer le mot de passe 
            </label>
            <input type="password" name="edit-confirm-password" id="edit-confirm-password"/>
        </fieldset>
        <fieldset>
            <label for="edit-roleId">
                 Modifier le rôle
            </label>
            <select name="edit-roleId" id="edit-roleId">
                <option value="1">User</option>
                <option value="2">Admin</option>
            </select>
        </fieldset>
        <fieldset>
            <button type="submit">
                Modifier le compte
            </button>
        </fieldset>
         <input type="hidden" name="edit-form" value="edit"/>
    </form>
</main> 