<section id="manage-user">
    <h2>Gestion des Utilisateurs</h2>
    <p class="message">
        <?php
            if(isset($_SESSION['message'])) {
                echo "<p>" .$_SESSION['message'] ."</p>";
                unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
            }
        ?>
    </p>
    <!--Fenetre Modale Delete-->
    <div id="deleteModal" class="modal">
        <div class="modal-content">
            <p>Êtes-vous sûr de vouloir supprimer cet utilisateur ?</p>
            <button id="confirmDelete" >Confirmer</button>
            <button id="cancelDelete">Annuler</button>
        </div>
    </div>
    <!--Affiche le formulaire d'edition si un id est selectionné -->
    <?php if (isset($_GET['edit']) && isset($_GET['id'])) : 
        require "./admin/user/edit.phtml";
    ?>
    
    <?php  else : ?>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
    <!--Ne pas oublier de préciser la clés ['user']-->
    <?php foreach ($data['users'] as $user) : ?>
                <tr>
                    <td><?= $user->getId(); ?></td>
                    <td><?= $user->getFirstName(); ?></td>
                    <td><?= $user->getLastName(); ?></td>
                    <td><?= $user->getEmail(); ?></td>
                    <td><?= $user->getRoleId(); ?></td>
                    <td>
                        <a href="index.php?route=admin_user_edit&id=<?= $user->getId(); ?>" class="edit-user-btn">Modifier</a>
                        <a href="index.php?route=admin_user_delete&id=<?= $user->getId(); ?>" class="delete-user-btn" data-user-id="<?= $user->getId(); ?>">Supprimer</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            <?php endif; ?>
            
            
        </tbody>
    </table>
    
    <a href="#">Ajouter un utilisateur</a>
    
    <a href="index.php?route=homepage">Retour à l'accueil</a>
</section>
