<main class="manage-admin">
    <section class="button-container">
        <a href="/ZERODEGRE_/admin/album" class="dashboard-button">Album (song)</a>
        <a href="/ZERODEGRE_/admin/artist" class="dashboard-button">Artiste</a>
        <a href="/ZERODEGRE_/admin/product" class="dashboard-button">Produits</a>
        <a href="/ZERODEGRE_/admin/post" class="dashboard-button">Article</a>
    </section>
    <h2>Gestion des Utilisateurs</h2>

    <?php
        if(isset($_SESSION['message'])) {
            echo "<p class='admin-message'>" .$_SESSION['message'] ."</p>";
            unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
        }
    ?>

    <!--Fenetre Modale Delete-->
    <div id="deleteModal" class="modal">
        <div class="modal-content">
            <p>Êtes-vous sûr de vouloir supprimer cet utilisateur ?</p>
            <button id="confirm-delete">Confirmer</button>
            <button id="cancel-delete">Annuler</button>
        </div>
    </div>
    <section class="admin-table-container">
        <table class="admin-table">
            <thead>
                <tr>
                        <th>ID</th>
                    <th>Prénom</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Rôle</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
        <?php foreach ($data['users'] as $user) : ?>
                    <tr>
                        <td><?= htmlspecialchars($user->getId()); ?></td>
                        <td><?= htmlspecialchars($user->getFirstName()); ?></td>
                        <td><?= htmlspecialchars($user->getLastName()); ?></td>
                        <td><?= htmlspecialchars($user->getEmail()); ?></td>
                        <?php if($user->getRoleId() === 2) : ?>
                        <td>Admin</td>
                        <?php else : ?>
                        <td>User</td>
                        <?php endif; ?>
                        <td>
                            <div class="admin-table-btn">
                                <a href="/ZERODEGRE_/admin/user/edit&id=<?= htmlspecialchars($user->getId()); ?>" class="edit-user-btn">Modifier</a>
                                <a class="open-modal" data-entity-id="<?= htmlspecialchars($user->getId()); ?>" data-entity-type="user">Supprimer</a>
                            </div>
                        </td>
                    </tr>
        <?php endforeach; ?>
            </tbody>
        </table>
    </section>
    <section class="admin-btn">
        <a href="/ZERODEGRE_/register">Ajouter un utilisateur</a>
        <a href="/ZERODEGRE_/admin/dashboard">Retour au Dashboard</a>
    </section>
    
    <script type="text/javascript" src="./../assets/js/admin_modal.js"></script>
</main>
    
