<section id="manage-user">
    <h2>Gestion des Utilisateurs</h2>
    <p class="message">
        <?php
            if(isset($_SESSION['message'])) {
                echo "<p>" .$_SESSION['message'] ."</p>";
                unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
            }
        ?>
    </p>

    <!--Fenetre Modale Delete-->
    <div id="deleteModal" class="modal">
        <div class="modal-content">
            <p>Êtes-vous sûr de vouloir supprimer cet utilisateur ?</p>
            <button id="confirm-delete">Confirmer</button>
            <button id="cancel-delete">Annuler</button>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <th>Rôle</th>
            </tr>
        </thead>
        <tbody id="userTableBody">
    <?php foreach ($data['users'] as $user) : ?>
                <tr>
                    <td><?= htmlspecialchars($user->getId()); ?></td>
                    <td><?= htmlspecialchars($user->getFirstName()); ?></td>
                    <td><?= htmlspecialchars($user->getLastName()); ?></td>
                    <td><?= htmlspecialchars($user->getEmail()); ?></td>
                    <td><?= htmlspecialchars($user->getRoleId()); ?></td>
                    <td>
                        <a href="index.php?route=admin_user_edit&id=<?= htmlspecialchars($user->getId()); ?>" class="edit-user-btn">Modifier</a>
                        <a class="open-modal" data-user-id="<?= htmlspecialchars($user->getId()); ?>">Supprimer</a>
                    </td>
                </tr>
    <?php endforeach; ?>
        </tbody>
    </table>
    
    <a href="#">Ajouter un utilisateur</a>
    
    <a href="index.php?route=homepage">Retour à l'accueil</a>
</section>
    <script type="text/javascript" src="./assets/js/index.js"></script>
