<footer class="footer">
    <section class="footer-container">
        <article class="footer-logo">
            <h1>ZERODEGRES_</h1>
        </article>
        <nav class="footer-nav">
            <a href="">MENTIONS LÉGALES</a>
            <a href="">CONTACTEZ-NOUS</a>
            <a href="">&copy; 2023. Tous droits réservés.</a>
        </nav>
        <article class="social-media">
            <a href="https://www.instagram.com/zerodegre_/"><i class="fa-brands fa-instagram fa-lg"></i></a>
            <a href="#"><i class="fa-brands fa-x-twitter fa-lg"></i></a>
        </article>
    </section>            
</footer>