<footer class="footer">
    <section class="footer-container">
        <article class="footer-logo">
            <h1>ZERODEGRES_</h1>
        </article>
        <nav class="footer-nav">
            <a title="Click to go to legal notice" aria-label="Click to go to legal notice" href="/ZERODEGRE_/legal-notice">MENTIONS LÉGALES</a>
            <a title="Click to go to legal contact us" aria-label="Click to go to legal contact us" href="#">CONTACTEZ-NOUS</a>
            <a href="">&copy; 2023. Tous droits réservés.</a>
        </nav>
        <article class="social-media">
            <a title="Instagram icon" aria-label="Instagram icon" href="https://www.instagram.com/zerodegre_/"><i class="fa-brands fa-instagram fa-lg"></i></a>
            <a title="X icon" aria-label="X icon" href="#"><i class="fa-brands fa-x-twitter fa-lg"></i></a>
        </article>
    </section>            
</footer>