<main class="main-legal-notice">
    <h2>Mentions légales</h2>
    <section>
        <h3>1. Informations sur le site web</h3>
        <p>Ce site web est la propriété du label Zéro Degré.</p>
    </section>
    <section>
        <h3>2. Contact</h3>
        <p>Pour toute question ou préoccupation concernant ce site web, veuillez nous contacter à l'adresse suivante : zerodegre@gmail.com</p>
    </section>
    <section>
        <h3>3. Hébergement</h3>
        <p>Ce site web est hébergé par [Nom de l'hébergeur] à l'adresse suivante : [Adresse de l'hébergeur].</p>
    </section>
    <section>
        <h3>4. Propriété intellectuelle</h3>
        <p>Tous les contenus présents sur ce site web, y compris les textes, les images, les vidéos, les logos et les éléments graphiques, sont la propriété exclusive de Zéro Degré et des membres du collectifs ou de tiers ayant autorisé Zéro Degré à les utiliser. Toute utilisation non autorisée de ces contenus est strictement interdite.</p>
    </section>
    <section>
        <h3>5. Utilisation du site web</h3>
        <ul>
            <li>Vous acceptez de ne pas utiliser ce site web à des fins illégales ou interdites par les lois en vigueur.</li>
            <li>Vous acceptez de ne pas perturber, endommager ou altérer le bon fonctionnement du site web.</li>
            <li>Vous acceptez de ne pas tenter d'accéder à des zones sécurisées du site web sans autorisation.</li>
        </ul>
    </section>
    <section>
        <h3>6. Liens externes</h3>
        <p>Ce site web peut contenir des liens vers des sites web tiers. Nous ne sommes pas responsables du contenu ou de la politique de confidentialité de ces sites web. Nous vous encourageons à consulter les mentions légales et la politique de confidentialité de tout site web auquel vous accédez via des liens depuis notre site.</p>
    </section>
    <section>
        <h3>7. Exonération de responsabilité</h3>
        <p>Bien que nous nous efforcions de maintenir les informations présentes sur ce site web à jour et exactes, nous ne donnons aucune garantie, explicite ou implicite, quant à l'exactitude, l'exhaustivité ou la fiabilité des informations fournies. Vous utilisez ce site web à vos propres risques.</p>
    </section>
    <section>
        <h3>8. Modification des mentions légales</h3>
        <p>Nous nous réservons le droit de modifier ces mentions légales à tout moment et sans préavis. Nous vous encourageons à consulter régulièrement cette page pour prendre connaissance des éventuelles modifications.</p>
    </section>
    <section>
        <h3>9. Droit applicable et juridiction compétente</h3>
        <p>Ces mentions légales sont régies par le droit français. Tout litige relatif à ce site web sera de la compétence exclusive des tribunaux de France.</p>
    </section>
</main>