<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin - Gestion des Articles</title>
</head>
<body>
    <h1>Gestion des Articles</h1>
    
<!-- Formulaire de création d'article -->
<h2>Créer un nouvel article</h2>
<form action="/admin/create_post" method="post">
    <fieldset>
        <legend>Informations de l'article</legend>
        <label for="title">Titre :</label>
        <input type="text" id="title" name="title" required><br>

        <label for="content">Contenu :</label>
        <textarea id="content" name="content" required></textarea><br>

        <label for="date">Date :</label>
        <input type="date" id="date" name="date" required><br>

        <label for="author">Auteur :</label>
        <input type="text" id="author" name="author" required><br>
    </fieldset>

    <fieldset>
        <legend>Informations additionnelles</legend>
        <label for="category_id">Catégorie :</label>
        <input type="number" id="category_id" name="category_id" required><br>

        <label for="media_id">ID du média :</label>
        <input type="number" id="media_id" name="media_id"><br>
    </fieldset>

    <input type="submit" value="Créer">
</form>

    
    <!-- Liste des articles existants -->
    <h2>Liste des Articles</h2>
    <table>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Contenu</th>
            <th>Date</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th>Média</th>
            <th>Actions</th>
        </tr>
        <?php foreach ($data['posts'] as $key => $post) : ?>
            <tr>
                <td><?= htmlspecialchars($post->getId()) ?></td>
                <td><?= htmlspecialchars($post->getTitle()) ?></td>
                <td><?= htmlspecialchars($post->getContent()) ?></td>
                <td><?= htmlspecialchars($post->getDate()) ?></td>
                <td><?= htmlspecialchars($post->getAuthor()) ?></td>
                <td><?= $data['categoriesNames'][$key]['name']  ?></td>
                <td><?= $data['mediasDesc'][$key]['alt_text'] ?></td>
                <td>
                    <a href="/admin/edit_post?id=<?= $post->getId() ?>">Modifier</a>
                    <a href="/admin/delete_post?id=<?= $post->getId() ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</body>
</html>
