<header>
    <nav>
        <ul>
            <li><a href="/ZERODEGRE_/register">Register</a></li>
            <li><a href="/ZERODEGRE_/admin/user">User</a></li>
            <li><a href="/ZERODEGRE_/admin/product">Product</a></li>
            <?php 
            if(isset($_SESSION['user'])){
            ?>
            <li><a href="/ZERODEGRE_/logout">Deconnexion</a></li> 
            <?php } else { ?>
            <li><a href="/ZERODEGRE_/login">Connexion</a></li>
            <?php } ?>
        </ul>
    </nav>
</header>