<header class="header-admin">
    <h1 class="header-admin-title"><a href="/ZERODEGRE_/admin/dashboard">ZERODEGRE_ // ADMIN</a></h1>
    <div id="header-admin-menu-button" class="close"></div>
</header>
<nav id="header-admin-menu">
    <ul>
        <li><a href="/ZERODEGRE_/register">Register</a></li>
            <li><a href="">Label</a></li>
            <li><a href="">Mixtape</a></li>
            <li><a href="">Blog</a></li>
            <li><a href="">Merch</a></li>
            <li><a href="/ZERODEGRE_/admin/dashboard">Admin</a></li>
        <?php 
        if(isset($_SESSION['user'])){
        ?>
        <li><a href="/ZERODEGRE_/logout">Deconnexion</a></li> 
        <?php } else { ?>
        <li><a href="/ZERODEGRE_/login">Connexion</a></li>
        <?php } ?>
    </ul>
</nav>
