<h2>Admin Dashboard</h2>
<main class="manage-admin">
    <section class="button-container">
        <a href="/ZERODEGRE_/admin/user" class="custom-button">Utilisateur</a>
        <a href="/ZERODEGRE_/admin/album" class="custom-button">Album (song)</a>
        <a href="/ZERODEGRE_/admin/artist" class="custom-button">Artiste</a>
        <a href="/ZERODEGRE_/admin/product" class="custom-button">Produits</a>
        <a href="/ZERODEGRE_/admin/post" class="custom-button">Article</a>
    </section>
</main>