
<main class="manage-admin">
    <h2>Admin Dashboard</h2>
    <section class="button-container">
        <a href="/ZERODEGRE_/admin/user" class="dashboard-button">Utilisateur</a>
        <a href="/ZERODEGRE_/admin/album" class="dashboard-button">Album (song)</a>
        <a href="/ZERODEGRE_/admin/artist" class="dashboard-button">Artiste</a>
        <a href="/ZERODEGRE_/admin/product" class="dashboard-button">Produits</a>
        <a href="/ZERODEGRE_/admin/post" class="dashboard-button">Article</a>
    </section>
</main>