<main id="edit-album" class="admin-form">
    <!-- Form for editing an existing album -->
    <h3>Editer un Album</h3>
    <p class="form-errors">
    <?php
        if(isset($data['errors']))
            echo $data["errors"][0];
            
    ?>
    </p>
    <form action="/ZERODEGRE_/admin/album/edit&id=<?= $_GET['id'] ?>" method="post">
        <fieldset>
            <label for="album-title">Titre de l'album:</label>
            <input type="text" id="album-title" name="album-title" value="<?= $data['album']->getTitre() ?>">
        </fieldset>
        <fieldset>
            <label for="album-year">Année:</label>
            <input type="number" id="album-year" name="album-year" value="<?= $data['album']->getYear() ?>">
        </fieldset>
        <fieldset>
            <label for="album-info">Info :</label>
            <input type="text" id="album-info" name="album-info" value="<?= $data['album']->getInfo() ?>">
        </fieldset>
        
        <h3>Modifier Media</h3>
            <?php if (!empty($data['media'])) : ?>
            <fieldset>
                <label for="album-url"> Url :</label>
                <input type="text" name="album-url" id="album-url" value="<?= $data['media']->getUrl() ?>">
            </fieldset>
            <fieldset>
                <label for="album-altText">Texte descriptif :</label>
                <input type="text" name="album-altText" id="album-altText" placeholder="Texte alternatif" value="<?= $data['media']->getAltText() ?>"/>
                <input type="hidden" name="albumMediaId" value="<?= $data['media']->getId() ?>">
            </fieldset>
            <?php else : ?>
            <fieldset>
                <label for="album-url"> Url :</label>
                <input type="text" name="album-url" id="album-url">
            </fieldset>
            <fieldset>
                <label for="album-altText">Texte descriptif :</label>
                <input type="text" name="album-altText" id="album-altText" placeholder="Texte alternatif"/>
                <input type="hidden" name="albumMediaId" value="">
            </fieldset>
            <?php endif ; ?>
            <fieldset>
                <button type="submit"> Modifier le l'album </button>
            </fieldset>
        <input type="hidden" name="album-edit-form" value="edit">
    </form>
    
    <!--Supprimer musique à l'unité-->
    <h3>Supprimer une chanson</h3>
    <form id="song-delete-form" method="post">
    <fieldset>
        <select id="songIdList" name="songIdList">
            <?php foreach ($data['song'] as $song) : ?>
                <option value="<?= $song->getId() ?>"><?= $song->getTitle() ?></option>
            <?php endforeach; ?>
        </select>
    </fieldset>
    <fieldset>
        <button type="submit" id="song-delete-btn" data-action="/ZERODEGRE_/admin/album/deleteSong&id=">Supprimer</button>
    </fieldset>
        <input type="hidden" name="song-delete-form"  value="submit"/>
    </form>

</main>
<script type="text/javascript" src="/ZERODEGRE_/assets/js/admin_modal.js"></script>