<section class="manage-admin">
    <!-- Form for editing an existing album -->
    <h2>Editer un Album</h2>
    <?php $album = $data['album'];
        $media = $data['media'];  
    ?>
    <p class="message">
        <?php
            if(isset($_SESSION['message'])) {
                echo $_SESSION['message'];
                unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque     rafraîchissement
            }
        ?>
    </p>
    <form action="/ZERODEGRE_/admin/album/edit&=<?= $_GET['id'] ?>" method="post">
        <label for="albumTitle">Album Title:</label>
        <input type="text" id="albumTitle" name="albumTitle" value="<?= $album->getTitre() ?>">
        <label for="albumYear">Year:</label>
        <input type="number" id="albumYear" name="albumYear" value="<?= $album->getYear() ?>">
        <?php if (!empty($media)) : ?>
            <label for="albumMediaUrl">Media URL:</label>
            <input type="text" id="albumMediaUrl" name="albumMediaUrl" value="<?= $media->getUrl() ?>">
            <label for="albumMediaAltText">Media Alt Text:</label>
            <input type="text" id="albumMediaAltText" name="albumMediaAltText" value="<?= $media    ->getAltText() ?>">           
        <?php else : ?>
            <label for="albumMediaUrl">Media URL:</label>
            <input type="text" id="albumMediaUrl" name="albumMediaUrl">
            <label for="albumMediaAltText">Media Alt Text:</label>
            <input type="text" id="albumMediaAltText" name="albumMediaAltText">
        <?php endif ; ?>
        <button type="submit">Edit Album</button>
        <input type="hidden" name="album-edit-form" value="submit"/>
    </form>
    
    <!--Supprimer musique à l'unité-->
    <form id="song-delete-form" method="post">
        <label for="songId">Choisis la musique à supprimer:</label>
        <select id="songIdList" name="songIdList">
            <?php foreach ($data['song'] as $song) : ?>
                <option value="<?= $song->getId() ?>"><?= $song->getTitle() ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit" id="song-delete-btn" data-action="/ZERODEGRE_/admin/album/deleteSong">Supprimer</button>
        <input type="hidden" name="song-delete-form"  value="submit"/>
    </form>
</section>