<main class="manage-admin">
    <section class="button-container">
        <a href="/ZERODEGRE_/admin/user" class="dashboard-button">Utilisateur</a>
        <a href="/ZERODEGRE_/admin/artist" class="dashboard-button">Artiste</a>
        <a href="/ZERODEGRE_/admin/product" class="dashboard-button">Produits</a>
        <a href="/ZERODEGRE_/admin/post" class="dashboard-button">Article</a>
    </section>
    <h2>Gestion des Albums et des chansons</h2>

    <?php
        if(isset($_SESSION['message'])) {
            echo "<p class='admin-message'>" .$_SESSION['message'] ."</p>";
            unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
        }
    ?>


    <!-- Liste des albums avec chansons -->
    <section class="admin-table-container"> 
        <table class="admin-table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Titre de l'album</th>
                    <th>Année de sortie</th>
                    <th>Info Générale</th>
                    <th>Chanson</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($data['albumsWithSongs'] as $album): ?>
                    <tr>
                        <td>
                            <?= $album->getId() ?>
                        </td>
                        <td>
                            <?= $album->getTitre() ?>
                        </td>
                        <td>
                            <?= $album->getYear() ?>
                        </td>
                        <td>
                            <?= $album->getInfo() ?>
                        </td>
                        <td>
                            <a class="album-toggle" href="#"onclick="toggleSongs(<?= $album->getId() ?>)">Voir les chansons</a>
                        </td>
                        <td>
                            <div class="admin-table-btn">
                                <a href="/ZERODEGRE_/admin/album/edit&id=<?= htmlspecialchars($album->getId()); ?>" class="edi-btn">Modifier</a>
                                <a class="open-modal" data-entity-id="<?= htmlspecialchars($album->getId()); ?>" data-entity-type="album">Supprimer</a>
                                <a href="/ZERODEGRE_/admin/album/addSong&id=<?= htmlspecialchars($album->getId()); ?>" class="add-song">Ajouter un son</a>
                            </div>
                        </td>
                    </tr>
                    <tr class="album-dropdown" data-album="<?= $album->getId() ?>">
                        <td colspan="2">
                            <ul class="album-song-list">
                                <?php foreach ($album->getSongs() as $song): ?>
                                    <li><?= $song->getTitle() ?> (<?= $song->getDuration() ?>)</li>
                                <?php endforeach; ?>
                            </ul>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section> 
    <section class="admin-btn">
        <a href="/ZERODEGRE_/admin/album/create">Ajouter un album</a>
        <a href="/ZERODEGRE_/admin/dashboard">Retour au Dashboard</a>
    </section> 
</main>
<script type="text/javascript" src="./../assets/js/admin_toggle.js"></script>
