<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>ZERODEGRE_</title>
    <link rel="stylesheet" href="/ZERODEGRE_/assets/styles/css/normalize.css" type="text/css">
    <link rel="stylesheet" href="/ZERODEGRE_/assets/styles/css/style.css" type="text/css" />
    <script src="https://kit.fontawesome.com/051e0c28d9.js" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png" sizes="96x96" href="/ZERODEGRE_/assets/img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/ZERODEGRE_/assets/img/favicon/favicon-16x16.png">
</head>
<body>
    <?php 
        if(isset($_SESSION["role"]) && $_SESSION["role"] === "Admin")
        {
            require 'templates/admin/partials/_header.phtml';
        } else {
            require 'templates/partials/_header.phtml';
        }
    ?>

    <?php require "templates/$template.phtml"; ?>
    
    <?php         
        if(isset($_SESSION["route"]) && $_SESSION["route"] !== "Admin")
            {
                require 'partials/_footer.phtml';
            }
    ?>

</body>
<script type="text/javascript" src="/ZERODEGRE_/assets/js/admin_toggle.js"></script>
</html>
