<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>ZERO DEGRE</title>
    <link rel="stylesheet" href="/ZERODEGRE_/assets/styles/css/normalize.css" type="text/css">
    <link rel="stylesheet" href="/ZERODEGRE_/assets/styles/css/style.css" type="text/css" />
</head>
<body>
    <?php 
        if(isset($_SESSION["role"]) && $_SESSION["role"] === "Admin")
        {
            require 'templates/admin/partials/_header.phtml';
        } else {
            require 'templates/partials/_header.phtml';
        }
    ?>

    <?php require "templates/$template.phtml"; ?>
    
    <?php 
        // if(isset($_SESSION["role"]) && $_SESSION["role"] === 2)
        // {
           
        // } else {
            require 'partials/_footer.phtml';
        // }
        ?>

</body>
<script type="text/javascript" src="/ZERODEGRE_/assets/js/admin_toggle.js"></script>
</html>
