<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>ZERO DEGRE</title>
    <link rel="stylesheet" href="./assets/styles/css/style.css" type="text/css" />
</head>
<body>
    
    <?php 
        // if($template !== "auth/login" && $template !== "auth/register")
        // {
            require 'templates/partials/_header.phtml';
        // }
    ?>
    <?php require "templates/$template.phtml"; ?>
    
    <?php 
    if($template !== "auth/login" && $template !== "auth/register")
    {
        require 'partials/_footer.phtml';
    }
        ?>
    <script type="text/javascript" src="./assets/js/index.js"></script>
</body>
</html>