<main class="main-post">
<section class="post-title">
    <h2>Viens découvrir nos dernières activitées !</h2>
    <p>ZeroDegrés ne se limite pas à la musique, c'est bien plus. Nous <span>produisont</span> des <span>artistes</span> et leur <span>musique</span>, nous menons des <span>actions culturelles</span> et <span>sociales inspirantes</span>, et offront des <span>concerts inoubliables</span> !! Le label est une véritable force créative dans le domaine musical et culturel.</p>
</section>
    <?php
        if(isset($_SESSION['message'])) {
            echo "<p class='admin-message'>" .$_SESSION['message'] ."</p>";
            unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
        }
    ?>
<section class="section-post">  
    <?php foreach ($data['postsWithMedias'] as $key => $post) : ?>
    <article class="article-post">
        <?php foreach($post->getMedia() as $media) :?>
        <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAltText() ?>">
        <?php endforeach;?>
        <p><?= $post->getAuthor() ?></p>
        <p><?= $data['categoriesNames'][$key]['name'] ?></p>
        <button class="show-post">
            <a title="Click to go to post <?=$post->getTitle()?>" aria-label="Click to go to post <?=$post->getTitle()?>" class="show-post-a" href="/ZERODEGRE_/post/show&id=<?= $post->getId() ?>">Découvrir l'article</a>
        </button>
    </article>
    <?php endforeach;?>
</section>
</main>