<main class="main-post">
    <article>
        <img src=""></img>
        <h3>Titre post</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda illum ducimus perspiciatis aut necessitatibus sequi quibusdam aliquam quidem officiis labore.</p>
        <!--Possibilité de créer generateUrl() en method router-->
        <button><a href="<?= index.php?route=product&id=<?= $productId ?>">Voir les détails du produits</a></button>
    </article>
</main>