<main class="main-show-post">
        <?php $article = $data['post'];
            $media = $article->getMedia();
        ?>
    <?php if ($article) : ?>
        <section class="container-show-post">
            <h2><?= $article->getTitle() ?></h2>
                <p class="author">Auteur : <?= $article->getAuthor() ?></p>
                <p class="category">Catégorie : <?= $data["categoryName"]['name'] ?></p>
                <p class="date">Date de publication : <?= $article->getDate() ?></p>
            <img src="<?= $media["0"]->getUrl() ?>" alt="<?= $media["0"]->getAltText() ?>">
            <p class="content"><?= $article->getContent() ?></p>
            <a title="Click to go back to post page" aria-label="Click to go back to post page" href="/ZERODEGRE_/post">Retour</a>
        </section>
    <?php else : ?>
        <p>L'article que vous cherchez n'existe pas.</p>
    <?php endif; ?>
</main>
