<main id="register">  
    <h2>Inscription</h2>
    <form action="/ZERODEGRE_/register" method="post">
        <p class="form-errors">
            <?php
                if(isset($data['errors']))
                    echo $data["errors"][0];
            ?>
        </p>
        <fieldset>
            <label for="register-firstName">
                Prénom
            </label>
            <input type="text" name="register-firstName" id="register-firstName"/>
        </fieldset>
        <fieldset>
            <label for="register-lastName">
                Nom
            </label>
            <input type="text" name="register-lastName" id="register-lastName"/>
        </fieldset>
        <fieldset>
            <label for="register-email">
                Email
            </label>
            <input type="email" name="register-email" id="register-email"/>
        </fieldset>
        <fieldset>
            <label for="register-password">
                Mot de passe
            </label>
            <input type="password" name="register-password" id="register-password"/>
        </fieldset>
        <fieldset>
            <label for="register-confirm-password">
                 Confirmer le mot de passe 
            </label>
            <input type="password" name="register-confirm-password" id="register-confirm-password"/>
        </fieldset>
        <fieldset>
            <button type="submit">
                Créer un compte
            </button>
        </fieldset>
         <input type="hidden" name="register-form" value="register"/>
    </form>
</main> 