<main id="create-rtist"class="admin-form">
    
    <form action="/ZERODEGRE_/admin/artist/create" method="post">
        <h2>Créer un nouvel artiste</h2>
        <fieldset>
            <label for="name">Nom de l'artiste:</label>
            <input type="text" id="name" name="name" required>
        </fieldset>
        <fieldset>
             <label for="description">Description:</label>
        <textarea id="description" name="description" required></textarea>
        </fieldset>
        <fieldset>
            <label for="roleId"> Modifier le rôle </label>
                <select name="roleId">
                    <option value="4">Beatmaker</option>
                    <option value="3">Rappeur</option>
                </select>
        </fieldset>
        <h3>Ajouter un média</h3>
        <fieldset>
            <label for="url"> Url </label>
            <input type="text" name="url" id="url" placeholder="Chemin/de/l'image">
        </fieldset>
        <fieldset>
            <label for="altText">Descriptif du média</label>
            <input type="text" name="altText" id="altText" placeholder="Text alternatif"/>
        </fieldset>
        <fieldset>
            <button type="submit">Créer Artiste</button>
        </fieldset>
        <input type="hidden" name="artist-form" value="submit"/>
    </form>
</main>
