<main class="manage-admin">
    <section class="button-container">
        <a title="Click to go to admin user page" aria-label="Click to go to admin user page" href="/ZERODEGRE_/admin/user" class="dashboard-button">Utilisateur</a>
        <a title="Click to go to admin album and song page" aria-label="Click to go to admin album and song page" href="/ZERODEGRE_/admin/album" class="dashboard-button">Album (song)</a>
        <a title="Click to go to admin post page" aria-label="Click to go to admin post page" href="/ZERODEGRE_/admin/post" class="dashboard-button">Article</a>
        <a title="Click to go to admin product page" aria-label="Click to go to admin product page" href="/ZERODEGRE_/admin/product" class="dashboard-button">Produits</a>
    </section>
    <h2>Gestion des Artistes</h2>

    <?php
        if(isset($_SESSION['message'])) {
            echo "<p class='admin-message'>" .$_SESSION['message'] ."</p>";
            unset($_SESSION['message']); // Effacer le message pour qu'il ne s'affiche pas à chaque rafraîchissement
        }
    ?>
    <!--Fenetre Modale Delete-->
    <div id="deleteModal" class="modal">
        <div class="modal-content">
            <p>Êtes-vous sûr de vouloir supprimer ce produit ?</p>
            <button id="confirm-delete">Confirmer</button>
            <button id="cancel-delete">Annuler</button>
        </div>
    </div>
    <section class="admin-table-container">
        <table class="admin-table" id="tableBody">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Description</th>
                    <th>Nom du média</th>
                    <th>Album</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody> 
                <?php foreach ($data['artistWithAlbum'] as $key => $artist) : ?>
                    <tr>
                        <!-- Il faut que je renvoit des objets Artist remplit ou non d'album // La difficulté va être de rajouter les médias  -->
                        <td><?= htmlspecialchars($artist->getId()) ?></td>
                        <td><?= htmlspecialchars($artist->getName()) ?></td>
                        <?php if($artist->getRoleId() === 3) : ?>
                        <td>Rappeur.euse</td>
                        <?php else : ?>
                        <td>Beatmaker.euse</td>
                        <?php endif; ?>
                        <td><?= htmlspecialchars($artist->getDescription()) ?></td>
                        <td><?= htmlspecialchars($data['mediaDesc'][$key]['alt_text']) ?></td>
                        <td>
                            <ul class="artist-album-list">
                                <?php foreach ($artist->getAlbums() as $album): ?>
                                    <li><?= $album->getTitre() ?></li>
                                <?php endforeach; ?>
                            </ul>
                            </td>
                        <td>
                            <div class="admin-table-btn">
                                <a title="Click to got to edit <?= $artist->getName() ?>" aria-label="Click to got to edit <?= $artist->getName() ?>" href="/ZERODEGRE_/admin/artist/edit&id=<?= $artist->getId() ?>">Modifier</a>
                                <a title="Click to got to remove <?= $artist->getName() ?>" aria-label="Click to got to remove <?= $artist->getName() ?>" href="/ZERODEGRE_/admin/artist/delete&id=<?= $artist->getId() ?>">Supprimer</a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="admin-btn">
            <a title="Click to got to create an artist" aria-label="Click to got to create an artist" href="/ZERODEGRE_/admin/artist/create">Créer un nouvel artiste</a>
            <a title="Click to got to admin dashboard" aria-label="Click to got to admin dashboard" href="/ZERODEGRE_/admin/dashboard">Retour au Dashboard</a>
        </div>
    </section>
</main>

